version: "2"
run:
  go: "1.23"
  timeout: 5m
  allow-parallel-runners: true
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dupl
    - errcheck
    - funlen
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 400
    funlen:
      lines: 200
      statements: 100
    gocritic:
      enabled-tags:
        - performance
      disabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - style
      settings:
        hugeParam:
          sizeThreshold: 170
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 140
    misspell:
      locale: US
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: unreachable-code
        - name: redefines-builtin-id
    staticcheck:
      checks:
        - -SA1019
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*_test.go$
      - tests_func
      - tmp
      - submodules
      - testtools
      - third_party$
      - builtin$
      - examples$
severity:
  default: error
  rules:
    - linters:
        - godox
        - unused
      severity: info
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - .*_test.go$
      - tests_func
      - tmp
      - submodules
      - testtools
      - third_party$
      - builtin$
      - examples$
