version: 2
project_name: cnpg-plugin-wal-g

release:
  github:
    owner: wal-g
    name: wal-g

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download

builds:
  - id: "walg-plugin"
    main: "./cmd/main.go"
    binary: "cnpg-plugin-wal-g"
    flags:
      - -trimpath
    ldflags:  # https://pkg.go.dev/cmd/go#hdr-Compile_packages_and_dependencies / https://pkg.go.dev/cmd/link
      - >-
        {{- if not .IsSnapshot }}
          -s -w
          {{- end }}
        -X github.com/wal-g/cnpg-plugin-wal-g/pkg/version.version={{.Version}} 
        -X github.com/wal-g/cnpg-plugin-wal-g/pkg/version.commitHash={{.ShortCommit}}
        -X github.com/wal-g/cnpg-plugin-wal-g/pkg/version.buildDate={{.Date}}
    goos:
      - linux  # Only linux currently supported due to wal-g building limitations
    goarch:
      - amd64  # Only amd64 currently supported due to wal-g building limitations

dist: output

archives:
  - formats: [ 'tar.gz' ]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

# The lines below are called `modelines`. See `:help modeline`
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj