apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client
spec:
  secretName: cnpg-plugin-wal-g-client-tls
  commonName: cnpg-plugin-wal-g-client
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  usages:
    - client auth
  issuerRef:
    name: cnpg-plugin-wal-g-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
