apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: backup-example
spec:
  method: plugin
  cluster:
    name: cluster-example  # Name of cluster to create backup from
  pluginConfiguration:
    name: cnpg-extensions.yandex.cloud  # Use plugin for backup creation (BackupConfig will be used from Cluster definition)
