---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-cnpg-extensions-yandex-cloud-v1beta1-backupconfig
  failurePolicy: Fail
  name: mbackupconfig-v1beta1.kb.io
  rules:
  - apiGroups:
    - cnpg-extensions.yandex.cloud
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backupconfigs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-cnpg-extensions-yandex-cloud-v1beta1-backupconfig
  failurePolicy: Fail
  name: vbackupconfig-v1beta1.kb.io
  rules:
  - apiGroups:
    - cnpg-extensions.yandex.cloud
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backupconfigs
  sideEffects: None
