# five node (4 workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cnpg-wal-g
networking:
  ipFamily: dual
  disableDefaultCNI: true  # Disable default CNI, use Cilium instead
nodes:
- role: control-plane
- role: worker
  extraMounts:  # add mount with loopback device of limited capacity
  - hostPath: /run/kind-cnpg-wal-g-volumes-mounts-1
    containerPath: /var/local-path-provisioner  # Directory used by local-path-provisioner 
- role: worker
  extraMounts:  # add mount with loopback device of limited capacity
  - hostPath: /run/kind-cnpg-wal-g-volumes-mounts-2
    containerPath: /var/local-path-provisioner  # Directory used by local-path-provisioner 
- role: worker
  extraMounts:  # add mount with loopback device of limited capacity
  - hostPath: /run/kind-cnpg-wal-g-volumes-mounts-3
    containerPath: /var/local-path-provisioner  # Directory used by local-path-provisioner 
- role: worker
  extraMounts:  # add mount with loopback device of limited capacity
  - hostPath: /run/kind-cnpg-wal-g-volumes-mounts-4
    containerPath: /var/local-path-provisioner  # Directory used by local-path-provisioner 
