# This rule is not used by the project cnpg-plugin-wal-g itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over cnpg-extensions.yandex.cloud.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cnpg-plugin-wal-g.fullname" . }}-backupconfig-admin-role
  labels:
    {{- include "cnpg-plugin-wal-g.labels" . | nindent 4 }}
rules:
- apiGroups:
  - cnpg-extensions.yandex.cloud
  resources:
  - backupconfigs
  verbs:
  - '*'
- apiGroups:
  - cnpg-extensions.yandex.cloud
  resources:
  - backupconfigs/status
  verbs:
  - get
