# This rule is not used by the project cnpg-plugin-wal-g itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the cnpg-extensions.yandex.cloud.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cnpg-plugin-wal-g.fullname" . }}-backupconfig-editor-role
  labels:
    {{- include "cnpg-plugin-wal-g.labels" . | nindent 4 }}
rules:
- apiGroups:
  - cnpg-extensions.yandex.cloud
  resources:
  - backupconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cnpg-extensions.yandex.cloud
  resources:
  - backupconfigs/status
  verbs:
  - get
