apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cnpg-plugin-wal-g.fullname" . }}-leader-election-rb
  labels:
    {{- include "cnpg-plugin-wal-g.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cnpg-plugin-wal-g.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "cnpg-plugin-wal-g.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
