apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cnpg-plugin-wal-g.fullname" . }}-metrics-reader
  labels:
    {{- include "cnpg-plugin-wal-g.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
