apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cnpg-plugin-wal-g.fullname" . }}-metrics-auth-rb
  labels:
    {{- include "cnpg-plugin-wal-g.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cnpg-plugin-wal-g.fullname" . }}-metrics-auth-role
subjects:
- kind: ServiceAccount
  name: {{ include "cnpg-plugin-wal-g.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
