apiVersion: cnpg-extensions.yandex.cloud/v1beta1
kind: BackupConfig
metadata:
  name: example-backup-config
spec:
  downloadConcurrency: 4
  downloadFileRetries: 15
  uploadDiskRateLimitBytesPerSecond: 7864320
  uploadNetworkRateLimitBytesPerSecond: 536870912
  uploadConcurrency: 4
  uploadDiskConcurrency: 4
  deltaMaxSteps: 7
  storage:
    type: s3
    s3:
      prefix: s3://endevir-test1/backups
      region: ru-central1
      endpointUrl: https://storage.yandexcloud.net
      forcePathStyle: false
      storageClass: STANDARD
      accessKeyId:
        name: "example-s3-credentials"
        key: "accessKey"
      accessKeySecret:
        name: "example-s3-credentials"
        key: "secret"
---
apiVersion: v1
kind: Secret
metadata:
  name: example-s3-credentials
type: Opaque
stringData:
  accessKey: CHANGEME
  secret: CHANGEME
