apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  plugins:
  - name: cnpg-extensions.yandex.cloud
    isWALArchiver: true
    parameters:
      backupConfig: example-backup-config
  storage:
    size: 1Gi
  postgresql:
    pg_hba:
      - local all all trust
      - local replication all trust
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-example
spec:
  schedule: "0 */30 * * * *"  # Each 30 minutes create backup
  backupOwnerReference: self
  cluster:
    name: cluster-example
  pluginConfiguration:
    name: cnpg-extensions.yandex.cloud
    parameters:
      backupConfig: example-backup-config
  immediate: true
