apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example-from-backup
spec:
  instances: 3
  imagePullPolicy: Always
  plugins:
  - name: cnpg-extensions.yandex.cloud
    isWALArchiver: true
    parameters:
      someParameterName: some-parameter-value
  storage:
    size: 1Gi
  bootstrap:
    recovery:
      source: walg-backup
  postgresql:
    pg_hba:
      - local all all trust
      - local replication all trust
  externalClusters:
  - name: walg-backup
    plugin:
      name: cnpg-extensions.yandex.cloud
      parameters:
        someParameterName: some-parameter-value
